# NumPy 한번에 제대로 배우기



---



## NumPy 특징

* Numerical Python의 약자
* 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
* 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
* 정교한 브로드캐스팅(broadcasting) 기능
* 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
* 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
* 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [2]:
import numpy as np
np.__version__

'1.18.5'



---



## 배열 생성

### 리스트로 배열 만들기


In [5]:
a1 = np.array([1,2,3,4,5]);
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0],a1[1],a1[2],a1[3],a1[4])
a1[0] = 4
a1[1] = 5
a1[2] = 6
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 5 6 4 5]


In [6]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)
print(a2.shape)
print(a2[0,0],a2[1,1],a2[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


In [17]:
a3 = np.array([   [[1,2,3],[4,5,6],[7,8,9]],
                  [[1,2,3],[4,5,6],[7,8,9]],
                  [[1,2,3],[4,5,6],[7,8,9]] ])
print(a3)
print(a3.shape)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


### 배열 생성 및 초기화

* `zeros()`: 모든 요소를 0으로 초기화

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

* `ones()`: 모든 요소를 1로 초기화

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

* `full()`: 모든 요소를 지정한 값으로 초기화

In [ ]:
np.full((3,3),1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

* `eye()`: 단위행렬(identity matrix) 생성
  + 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

* `tri()`: 삼각행렬 생성

In [3]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

* `empty()`: 초기화되지 않은 배열 생성
  + 초기화가 없어서 배열 생성비용 저렴하고 빠름
  + 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [4]:
np.empty(10)

array([2.74256393e-316, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000])

* `_like()`: 지정된 배열과 shape가 같은 행렬 생성
  + `np.zeros_like()`
  + `np.ones_like()`
  + `np.full_like()`
  + `np.empty_like()`

In [12]:
print(a1)
np.zeros_like(a1)

[4 5 6 4 5]


array([0, 0, 0, 0, 0])

In [15]:
print(a2)
np.ones_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
print(a3)
np.full_like(a3,10)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

### 생성한 값으로 배열 생성

* `arange()`: 정수 범위로 배열 생성

In [20]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

* `linspace()`: 범위 내에서 균등 간격의 배열 생성

In [21]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

* `logspace()`: 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [22]:
np.logspace(0.1,1,20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

### 랜덤값으로 배열 생성


* `random.random()`: 랜덤한 수의 배열 생성

In [24]:
np.random.random((3,3))

array([[0.01579989, 0.76657974, 0.64378268],
       [0.87414099, 0.27103403, 0.13357252],
       [0.27164131, 0.65438196, 0.93111402]])

* `random.randint()`: 일정 구간의 랜덤 정수의 배열 생성

In [25]:
np.random.randint(0,10,(3,3))

array([[9, 1, 1],
       [6, 0, 9],
       [2, 6, 6]])

* `random.normal()`: 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성
* 평균=0, 표준편차=1, 3 x 3 배열

In [26]:
np.random.normal(0,10,(3,3))

array([[  1.16191167,  -9.44484824,   1.42667849],
       [-12.16107127,   8.95728036,  -8.79541963],
       [ 22.19750612, -16.13457299,   3.68297238]])

* `random.rand()`: 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성

In [29]:
np.random.rand(3,3)

array([[0.53608744, 0.41151848, 0.30757972],
       [0.65642304, 0.1718646 , 0.02469507],
       [0.53473537, 0.57713266, 0.93312562]])

* `random.randn()`: 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성

In [33]:
np.random.randn(3,3)

array([[-0.79079123,  0.92099497,  1.33449887],
       [-0.28654206, -0.7848586 , -0.78099956],
       [-0.63421582,  2.31483547,  0.49541911]])

### 표준 데이터 타입

In [35]:
np.zeros(20,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [39]:
np.full((3,3),1.0,dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 날짜/시간 배열 생성


In [41]:
date = np.array("2020-01-01",dtype=np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [42]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [43]:
datetime = np.datetime64("2020-01-01 12:00")
datetime

numpy.datetime64('2020-01-01T12:00')

In [45]:
datetime = np.datetime64("2020-06-01 12:00:12.34","ns")
datetime

numpy.datetime64('2020-06-01T12:00:12.340000000')



---



## 배열 조회

### 배열 속성 정보

In [48]:
def array_info(array):
  print(array)
  print("ndim", array.ndim)
  print("shape", array.dtype)
  print("size", array.size)
  print("itemsize", array.itemsize)
  print("nbytes",array.nbytes)
  print("strides", array.strides)


In [49]:
array_info(a1)

[4 5 6 4 5]
ndim 1
shape int64
size 5
itemsize 8
nbytes 40
strides (8,)


In [50]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim 2
shape int64
size 9
itemsize 8
nbytes 72
strides (24, 8)


In [51]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim 3
shape int64
size 27
itemsize 8
nbytes 216
strides (72, 24, 8)


### 인덱싱(Indexing)

In [52]:
print(a1)
print(a1[0])
print(a1[1])
print(a1[2])
print(a1[-1])
print(a1[-2])

[4 5 6 4 5]
4
5
6
5
4


In [53]:
print(a2)
print(a2[0,0])
print(a2[0,2])
print(a2[1,1])
print(a2[1,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
5
5


In [54]:
print(a3)
print(a3[0,0,0])
print(a3[1,1,1])
print(a3[2,2,2])
print(a3[2,-1,-1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
5
9
9


### 슬라이싱(Slicing)

* 슬라이싱 구문: `a[start:stop:step]`
* 기본값: start=0, stop=ndim, step=1

In [55]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[::2])
print(a1[::-1])

[4 5 6 4 5]
[4 5]
[4 5 6 4 5]
[4]
[4 6 5]
[5 4 6 5 4]


In [56]:
print(a2)
print(a2[1])
print(a2[1, :])
print(a2[:2, :2])
print(a2[1:, ::-1])
print(a2[::-1,::-1])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### 불리언 인덱싱(Boolean Indexing)

* 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
* True 값인 인덱스의 값만 조회

In [59]:
print(a1)
bi = [False, True, True, False, True]
print(a1[bi])
bi = [True,False,True,True,False]
print(a1[bi])


[4 5 6 4 5]
[5 6 5]
[4 6 4]


In [61]:
print(a2)
bi = np.random.randint(0,2,(3,3),dtype=bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False  True  True]
 [ True  True  True]
 [ True False False]]
[2 3 4 5 6 7]


### 팬시 인덱싱(Fancy Indedxing)

In [68]:
print(a1)
print([a1[0],a1[2]])
ind = [0,2]
print(a1[ind])
ind = np.array([[0,1],
               [2,0]])
print(a1[ind])

[4 5 6 4 5]
[4, 6]
[4 6]
[[4 5]
 [6 4]]


In [70]:
print(a2)
raw = np.array([0,2])
col = np.array([1,2])
print(a2[raw,col])
print(a2[raw,:])
print(a2[:,col])
print(a2[raw,1])
print(a2[2,col])
print(a2[raw,1:])
print(a2[1:,col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[2 8]
[8 9]
[[2 3]
 [8 9]]
[[5 6]
 [8 9]]




---



## 배열 값 삽입/수정/삭제/복사

### 배열 값 삽입

* `insert()`: 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원 배열로 변환
* 추가할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [76]:
print(a1)
b1=np.insert(a1,0,10)
print(b1)
print(a1)
c1=np.insert(a1,2,10)
print(c1)

[4 5 6 4 5]
[10  4  5  6  4  5]
[4 5 6 4 5]
[ 4  5 10  6  4  5]


In [77]:
print(a2)
b2 = np.insert(a2,1,10,axis=0)
print(b2)
c2 = np.insert(a2,1,10,axis=1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정

* 배열의 인덱싱으로 접근하여 값 수정

In [79]:
print(a1)
a1[0] = 1
a1[1] = 2
a1[2] = 3
print(a1)
a1[:1] = 9
print(a1)
i = np.array([1,3,4])
a1[i] = 0
print(a1)
a1[i] +=4
print(a1)

[1 2 3 4 5]
[1 2 3 4 5]
[9 2 3 4 5]
[9 0 3 0 0]
[9 4 3 4 4]


In [83]:
print(a2)
a2[0,0] = 1
a2[1,1] = 2
a2[2,2] = 3
a2[0] = 1
print(a2)
a2[1:,2] = 0
print(a2)
row = np.array([0,1])
col = np.array([1,2])
a2[row,col] = 0
print(a2)

[[1 1 1]
 [4 2 0]
 [7 8 0]]
[[1 1 1]
 [4 2 0]
 [7 8 3]]
[[1 1 1]
 [4 2 0]
 [7 8 0]]
[[1 0 1]
 [4 2 0]
 [7 8 0]]


### 배열 값 삭제

* `delete()`: 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차원 배열로 변환
* 삭제할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [85]:
print(a1)
b1 = np.delete(a1,1)
print(b1)
print(a1)

[9 4 3 4 4]
[9 3 4 4]
[9 4 3 4 4]


In [86]:
print(a2)
b2 = np.delete(a2,1,axis=0)
print(b2)
c2 = np.delete(a2,1,axis=1)
print(c2)

[[1 0 1]
 [4 2 0]
 [7 8 0]]
[[1 0 1]
 [7 8 0]]
[[1 1]
 [4 0]
 [7 0]]


### 배열 복사

* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [90]:
print(a2)
print(a2[:2,:2])
a2_sub = a2[:2,:2]
print(a2_sub)
a2_sub[:,1] = 0
print(a2_sub)
print(a2)

[[1 0 1]
 [4 0 0]
 [7 8 0]]
[[1 0]
 [4 0]]
[[1 0]
 [4 0]]
[[1 0]
 [4 0]]
[[1 0 1]
 [4 0 0]
 [7 8 0]]



* `copy()`: 배열이나 하위 배열 내의 값을 명시적으로 복사

In [92]:
print(a2)
a2_sub_copy = a2[:2, :2].copy()
print(a2_sub_copy)
a2_sub_copy[:,1] = 1
print(a2_sub_copy)
print(a2)

[[1 0 1]
 [4 0 0]
 [7 8 0]]
[[1 0]
 [4 0]]
[[1 1]
 [4 1]]
[[1 0 1]
 [4 0 0]
 [7 8 0]]




---



## 배열 변환

### 배열 전치 및 축 변경

In [94]:
print(a2)
print(a2.T)

[[1 0 1]
 [4 0 0]
 [7 8 0]]
[[1 4 7]
 [0 0 8]
 [1 0 0]]


In [95]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [96]:
print(a2)
print(a2.swapaxes(1,0))

[[1 0 1]
 [4 0 0]
 [7 8 0]]
[[1 4 7]
 [0 0 8]
 [1 0 0]]


In [97]:
print(a3)
print(a3.swapaxes(0,1))
print(a3.swapaxes(1,2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


### 배열 재구조화


* `reshape()`: 배열의 형상을 변경

In [98]:
n1 = np.arange(1,10)
print(n1)
print(n1.reshape(3,3))


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


* `newaxis()`: 새로운 축 추가

In [99]:
print(n1)
print(n1[np.newaxis, :5])
print(n1[:5, np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### 배열 크기 변경

* 배열 모양만 변경

In [101]:
n2 = np.random.randint(0,10, (2,5))
print(n2)
n2.resize((5,2))
print(n2)

[[8 7 4 2 1]
 [6 9 6 5 2]]
[[8 7]
 [4 2]
 [1 6]
 [9 6]
 [5 2]]


* 배열 크기 증가
* 남은 공간은 0으로 채워짐

In [103]:
n2.resize((5,5))
print(n2)

[[8 7 4 2 1]
 [6 9 6 5 2]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


* 배열 크기 감소
* 포함되지 않은 값은 삭제됨

In [104]:
n2.resize((3,3))
print(n2)

[[8 7 4]
 [2 1 6]
 [9 6 5]]


### 배열 추가

* `append()`: 배열의 끝에 값 추가

In [105]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.arange(10,19).reshape(3,3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


* axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [106]:
c2 = np.append(a2,b2)
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


* axis를 0으로 지정
* shape[0]을 제외한 나머지 shape은 같아야 함

In [107]:
c2 = np.append(a2,b2,axis = 0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


* axis를 1로 지정
* shape[1]을 제외한 나머지 shape은 같아야 함

In [108]:
c2 = np.append(a2,b2,axis = 1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### 배열 연결

* `concatenate()`: 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [109]:
a1 = np.array([1,3,5])
b1 = np.array([2,4,6])
np.concatenate([a1,b1])


array([1, 3, 5, 2, 4, 6])

In [110]:
c1 = np.array([7,8,9])
np.concatenate([a1,b1,c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [111]:
a2 = np.array([[1,2,3],
              [4,5,6]])
np.concatenate([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [112]:
a2 = np.array([[1,2,3],
              [4,5,6]])
np.concatenate([a2,a2],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `vstack()`: 수직 스택(vertical stack), 1차원으로 연결

In [113]:
np.vstack([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

* `hstack()`: 수평 스택(horizontal stack), 2차원으로 연결

In [114]:
np.hstack([a2,a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `dstack()`: 깊이 스택(depth stack), 3차원으로 연결

In [115]:
np.dstack([a2,a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

* `stack()`: 새로운 차원으로 연결

In [116]:
np.stack([a2,a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

### 배열 분할

* `split()`: 배열 분할

In [120]:
a1 = np.arange(0,10)
print(a1)
b1,c1 = np.split(a1,[5])
print(b1,c1)
b1,c1,d1,e1,f1 = np.split(a1,[2,4,6,8])
print(b1,c1,d1,e1,f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


* `vsplit()`: 수직 분할, 1차원으로 분할

In [122]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2,c2 = np.vsplit(a2,[2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


* `hsplit()`: 수평 분할, 2차원으로 분할

In [123]:
a2 = np.arange(1,28).reshape(3,3,3)
print(a2)
b2,c2 = np.hsplit(a2,[2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


* `dsplit()`: 깊이 분할, 3차원으로 분할

In [125]:
a3 = np.arange(1,28).reshape(3,3,3)
print(a3)
b3,c3 = np.hsplit(a2,[3])
print(b3)
print(c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[]




---



## 배열 연산

* NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용
* 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
* 배열 요소에 대한 반복적인 계산을 효율적으로 수행

### 브로드캐스팅(Broadcasting)

In [128]:
a1 = np.array([1,2,3])
print(a1)
print(a1 + 5)

a2 = np.arange(1,10).reshape(3,3)
print(a2)
print(a1+a2)

b2 = np.array([1,2,3]).reshape(3,1)
print(b2)
print(a1+b2)

[1 2 3]
[6 7 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


### 산술 연산(Arithmetic Operators)

In [137]:
a1 = np.arange(1,10)
print(a1)
print(a1 + 1)
print(np.add(a1, 10))
print(a1 - 2)
print(np.subtract(a1,10))
print(-a1)
print(np.negative(a1))
print(a1 * 2)
print(np.multiply(a1,2))
print(a1/2)
print(np.divide(a1,2))
print(a1 //2 )
print(np.floor_divide(a1,2))
print(a1 ** 2)
print(np.power(a1,2))
print(a1 % 2)
print(np.mod(a1,2))

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]
[-1  0  1  2  3  4  5  6  7]
[-9 -8 -7 -6 -5 -4 -3 -2 -1]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81]
[1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1]


In [138]:
a1 = np.arange(1,10)
print(a1)
b1 = np.random.randint(1,10,size=9)
print(b1)
print(a1 + b1)
print(a1 - b1)
print(a1 * b1)
print(a1 / b1)
print(a1 // b1)
print(a1 % b1)
print(a1 ** b1)

[1 2 3 4 5 6 7 8 9]
[5 1 1 4 2 3 8 1 9]
[ 6  3  4  8  7  9 15  9 18]
[-4  1  2  0  3  3 -1  7  0]
[ 5  2  3 16 10 18 56  8 81]
[0.2   2.    3.    1.    2.5   2.    0.875 8.    1.   ]
[0 2 3 1 2 2 0 8 1]
[1 0 0 0 1 0 7 0 0]
[        1         2         3       256        25       216   5764801
         8 387420489]


In [139]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.random.randint(1,10,size=(3,3))
print(b2)
print(a2+b2)
print(a2-b2)
print(a2*b2)
print(a2/b2)
print(a2//b2)
print(a2**b2)
print(a2%b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 2 6]
 [5 8 4]
 [4 9 8]]
[[ 5  4  9]
 [ 9 13 10]
 [11 17 17]]
[[-3  0 -3]
 [-1 -3  2]
 [ 3 -1  1]]
[[ 4  4 18]
 [20 40 24]
 [28 72 72]]
[[0.25       1.         0.5       ]
 [0.8        0.625      1.5       ]
 [1.75       0.88888889 1.125     ]]
[[0 1 0]
 [0 0 1]
 [1 0 1]]
[[        1         4       729]
 [     1024    390625      1296]
 [     2401 134217728  43046721]]
[[1 0 3]
 [4 5 2]
 [3 8 1]]


#### 절대값 함수(Absolute Function)

* `absolute()`, `abs()`: 내장된 절대값 함수

In [140]:
a1 = np.random.randint(-10,10,size = 5)
print(a1)
print(np.absolute(a1))
print(np.abs(a1))

[-1  5 -1 -4  8]
[1 5 1 4 8]
[1 5 1 4 8]


#### 제곱/제곱근 함수

* `square`, `sqrt`: 제곱, 제곱근 함수

In [142]:
print(a1)
print(np.square(a1))
print(np.sqrt(a1))

[-1  5 -1 -4  8]
[ 1 25  1 16 64]
[       nan 2.23606798        nan        nan 2.82842712]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


#### 지수와 로그 함수 (Exponential and Log Function)

In [143]:
a1 = np.random.randint(1,10, size=5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1))
print(np.power(a1,2))

[2 8 5 5 8]
[   7.3890561  2980.95798704  148.4131591   148.4131591  2980.95798704]
[  4. 256.  32.  32. 256.]
[ 4 64 25 25 64]


In [144]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[2 8 5 5 8]
[0.69314718 2.07944154 1.60943791 1.60943791 2.07944154]
[1.         3.         2.32192809 2.32192809 3.        ]
[0.30103    0.90308999 0.69897    0.69897    0.90308999]


#### 삼각 함수(Trigonometrical Function)


In [146]:
t = np.linspace(0,np.pi,3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))


[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [147]:
x = [-1, 0, 1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))


[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


### 집계 함수(Aggregate Functions)

#### sum(): 합 계산

In [150]:
a2 = np.random.randint(1,10, size=(3,3))
print(a2)
print(a2.sum(),np.sum(a2))
print(a2.sum(axis=0),np.sum(a2,axis=0))
print(a2.sum(axis=1),np.sum(a2,axis=1))


[[4 6 9]
 [2 4 4]
 [7 8 9]]
53 53
[13 18 22] [13 18 22]
[19 10 24] [19 10 24]


#### cumsum(): 누적합 계산

In [151]:
print(a2)
print(np.cumsum(a2))
print(np.cumsum(a2,axis=0))
print(np.cumsum(a2,axis=1))


[[4 6 9]
 [2 4 4]
 [7 8 9]]
[ 4 10 19 21 25 29 36 44 53]
[[ 4  6  9]
 [ 6 10 13]
 [13 18 22]]
[[ 4 10 19]
 [ 2  6 10]
 [ 7 15 24]]


#### diff(): 차분 계산

In [152]:
print(a2)
print(np.diff(a2))
print(np.diff(a2,axis=0))
print(np.diff(a2,axis=1))


[[4 6 9]
 [2 4 4]
 [7 8 9]]
[[2 3]
 [2 0]
 [1 1]]
[[-2 -2 -5]
 [ 5  4  5]]
[[2 3]
 [2 0]
 [1 1]]


#### prod(): 곱 계산

In [153]:
print(a2)
print(np.prod(a2))
print(np.prod(a2,axis=0))
print(np.prod(a2,axis=1))


[[4 6 9]
 [2 4 4]
 [7 8 9]]
3483648
[ 56 192 324]
[216  32 504]


#### cumprod(): 누적곱 계산

In [154]:
print(a2)
print(np.cumprod(a2))
print(np.cumprod(a2,axis=0))
print(np.cumprod(a2,axis=1))


[[4 6 9]
 [2 4 4]
 [7 8 9]]
[      4      24     216     432    1728    6912   48384  387072 3483648]
[[  4   6   9]
 [  8  24  36]
 [ 56 192 324]]
[[  4  24 216]
 [  2   8  32]
 [  7  56 504]]


#### dot()/matmul(): 점곱/행렬곱 계산

In [155]:
print(a2)
b2 = np.ones_like(a2)
print(b2)
print(np.dot(a2,b2))
print(np.matmul(a2,b2))

[[4 6 9]
 [2 4 4]
 [7 8 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[19 19 19]
 [10 10 10]
 [24 24 24]]
[[19 19 19]
 [10 10 10]
 [24 24 24]]


#### tensordot(): 텐서곱 계산

In [156]:
print(a2)
print(b2)
print(np.tensordot(a2,b2))
print(np.tensordot(a2,b2,axes = 0))
print(np.tensordot(a2,b2,axes = 1))

[[4 6 9]
 [2 4 4]
 [7 8 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
53
[[[[4 4 4]
   [4 4 4]
   [4 4 4]]

  [[6 6 6]
   [6 6 6]
   [6 6 6]]

  [[9 9 9]
   [9 9 9]
   [9 9 9]]]


 [[[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[4 4 4]
   [4 4 4]
   [4 4 4]]

  [[4 4 4]
   [4 4 4]
   [4 4 4]]]


 [[[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]

  [[9 9 9]
   [9 9 9]
   [9 9 9]]]]
[[19 19 19]
 [10 10 10]
 [24 24 24]]


#### cross(): 벡터곱

In [157]:
x = [1,2,3]
y = [4,5,6]
print(np.cross(x,y))

[-3  6 -3]


#### inner()/outer(): 내적/외적

In [158]:
print(a2)
print(b2)
print(np.inner(a2,b2))
print(np.outer(a2,b2))

[[4 6 9]
 [2 4 4]
 [7 8 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[19 19 19]
 [10 10 10]
 [24 24 24]]
[[4 4 4 4 4 4 4 4 4]
 [6 6 6 6 6 6 6 6 6]
 [9 9 9 9 9 9 9 9 9]
 [2 2 2 2 2 2 2 2 2]
 [4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4]
 [7 7 7 7 7 7 7 7 7]
 [8 8 8 8 8 8 8 8 8]
 [9 9 9 9 9 9 9 9 9]]


#### mean(): 평균 계산

In [160]:
print(a2)
print(np.mean(a2))
print(np.mean(a2,axis=0))
print(np.mean(a2,axis=1))


[[4 6 9]
 [2 4 4]
 [7 8 9]]
5.888888888888889
[4.33333333 6.         7.33333333]
[6.33333333 3.33333333 8.        ]


#### std(): 표준 편차 계산

In [161]:
print(a2)
print(np.std(a2))
print(np.std(a2,axis=0))
print(np.std(a2,axis=1))


[[4 6 9]
 [2 4 4]
 [7 8 9]]
2.3778816176702997
[2.05480467 1.63299316 2.3570226 ]
[2.05480467 0.94280904 0.81649658]


#### var(): 분산 계산

In [162]:
print(a2)
print(np.var(a2))
print(np.var(a2,axis=0))
print(np.var(a2,axis=1))


[[4 6 9]
 [2 4 4]
 [7 8 9]]
5.65432098765432
[4.22222222 2.66666667 5.55555556]
[4.22222222 0.88888889 0.66666667]


#### min(): 최소값

In [163]:
print(a2)
print(np.min(a2))
print(np.min(a2,axis=0))
print(np.min(a2,axis=1))


[[4 6 9]
 [2 4 4]
 [7 8 9]]
2
[2 4 4]
[4 2 7]


#### max(): 최대값

In [164]:
print(a2)
print(np.max(a2))
print(np.max(a2,axis=0))
print(np.max(a2,axis=1))


[[4 6 9]
 [2 4 4]
 [7 8 9]]
9
[7 8 9]
[9 4 9]


#### argmin(): 최소값 인덱스

In [165]:
print(a2)
print(np.argmin(a2))
print(np.argmin(a2,axis=0))
print(np.argmin(a2,axis=1))


[[4 6 9]
 [2 4 4]
 [7 8 9]]
3
[1 1 1]
[0 0 0]


#### argmax(): 최대값 인덱스

In [166]:
print(a2)
print(np.argmax(a2))
print(np.argmax(a2,axis=0))
print(np.argmax(a2,axis=1))


[[4 6 9]
 [2 4 4]
 [7 8 9]]
2
[2 2 0]
[2 1 2]


#### median(): 중앙값

In [167]:
print(a2)
print(np.median(a2))
print(np.median(a2,axis=0))
print(np.median(a2,axis=1))


[[4 6 9]
 [2 4 4]
 [7 8 9]]
6.0
[4. 6. 9.]
[6. 4. 8.]


#### percentile(): 백분위 수



In [168]:
a1 = np.array([0,1,2,3])
print(a1)
print(np.percentile(a1, [0,20,40,60,80,100], interpolation = 'linear'))
print(np.percentile(a1, [0,20,40,60,80,100], interpolation = 'higher'))
print(np.percentile(a1, [0,20,40,60,80,100], interpolation = 'lower'))
print(np.percentile(a1, [0,20,40,60,80,100], interpolation = 'nearest'))
print(np.percentile(a1, [0,20,40,60,80,100], interpolation = 'midpoint'))

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


#### any()

In [169]:
a2 = np.array([[False,False,False],
              [False,True,True],
              [False,True,True]])
print(a2)
print(np.any(a2))
print(np.any(a2,axis=0))
print(np.any(a2,axis=1))

[[False False False]
 [False  True  True]
 [False  True  True]]
True
[False  True  True]
[False  True  True]


#### all()

In [171]:
a2 = np.array([[False,False,True],
              [True,True,True],
              [False,True,True]])
print(a2)
print(np.all(a2))
print(np.all(a2,axis=0))
print(np.all(a2,axis=1))

[[False False  True]
 [ True  True  True]
 [False  True  True]]
False
[False False  True]
[False  True False]


### 비교 연산(Comparison Operators)


In [175]:
a1 = np.arange(1,10)
print(a1)
print(a1 == 5)
print(a1 != 5)
print(a1 < 5)
print(a1 <= 5)
print(a1 > 5)
print(a1 >= 5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True False False False False False]
[ True  True  True  True  True False False False False]
[False False False False False  True  True  True  True]
[False False False False  True  True  True  True  True]


In [179]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
print(np.sum(a2))
print(np.count_nonzero(a2 > 5))
print(np.sum(a2 > 5,axis=0))
print(np.sum(a2 > 5,axis=1))
print(np.any(a2 > 5))
print(np.any(a2 > 5,axis =0))
print(np.any(a2 > 5,axis = 1))
print(np.all(a2>5))
print(np.all(a2 > 5, axis=0))
print(np.all(a2 >5, axis=1))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
[1 1 2]
[0 1 3]
True
[ True  True  True]
[False  True  True]
False
[False False False]
[False False  True]


In [181]:
a1 = np.array([1,2,3,4,5])
print(a1)
b1= np.array([1,2,3,3,4])
print(b1)
print(np.isclose(a1,b1))

[1 2 3 4 5]
[1 2 3 3 4]
[ True  True  True False False]


In [184]:
a1 = np.array([np.nan,2,np.inf,4,np.NINF])
print(a1)
print(np.isnan(a1))
print(np.isinf(a1))
print(np.isfinite(a1))

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


#### 불리언 연산자(Boolean Operators)


In [189]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)

print((a2 > 5) & (a2 < 8))
print(a2[(a2 > 5) & (a2 < 8)])

print((a2 > 5) | (a2 < 8))
print(a2[(a2 > 5) | (a2 < 8)])

print((a2 > 5) ^ (a2 < 8))
print(a2[(a2 > 5) ^ (a2 < 8)])

print(~(a2 > 5))
print(a2[~(a2 > 5)])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True False False]]
[6 7]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True False]
 [False  True  True]]
[1 2 3 4 5 8 9]
[[ True  True  True]
 [ True  True False]
 [False False False]]
[1 2 3 4 5]


### 배열 정렬

In [191]:
a1 = np.random.randint(1, 10, size=10)
print(a1)
print(np.sort(a1))
print(a1)
print(np.argsort(a1))
print(a1)
print(a1.sort())
print(a1)

[5 6 2 7 6 8 8 6 2 4]
[2 2 4 5 6 6 6 7 8 8]
[5 6 2 7 6 8 8 6 2 4]
[2 8 9 0 1 4 7 3 5 6]
[5 6 2 7 6 8 8 6 2 4]
None
[2 2 4 5 6 6 6 7 8 8]


In [193]:
a2 = np.random.randint(1,10,size=(3,3))
print(a2)
print(np.sort(a2,axis=0))
print(np.sort(a2,axis=1))

[[3 8 8]
 [2 7 5]
 [6 7 8]]
[[2 7 5]
 [3 7 8]
 [6 8 8]]
[[3 8 8]
 [2 5 7]
 [6 7 8]]


#### 부분 정렬

* `partition()`: 배열에서 k개의 작은 값을 반환

In [194]:
a1 = np.random.randint(1,10,size=10)
print(a1)
print(np.partition(a1,3))

[7 4 2 7 9 5 5 9 7 2]
[4 2 2 5 7 5 7 9 7 9]


In [196]:
a2 = np.random.randint(1,10,size=(5,5))
print(a2)
print(np.partition(a2,3))
print(np.partition(a2,3,axis=0))
print(np.partition(a2,3,axis=1))


[[2 2 8 4 5]
 [9 7 5 1 3]
 [4 5 9 6 3]
 [5 8 4 9 6]
 [3 9 9 1 2]]
[[4 2 2 5 8]
 [1 3 5 7 9]
 [3 4 5 6 9]
 [4 5 6 8 9]
 [1 2 3 9 9]]
[[2 2 4 1 2]
 [3 5 8 1 3]
 [4 7 5 4 3]
 [5 8 9 6 5]
 [9 9 9 9 6]]
[[4 2 2 5 8]
 [1 3 5 7 9]
 [3 4 5 6 9]
 [4 5 6 8 9]
 [1 2 3 9 9]]


## 배열 입출력


In [198]:
a2 = np.random.randint(1,10,size=(5,5))
print(a2)

np.save("a",a2)

[[4 4 1 5 7]
 [8 3 9 7 6]
 [1 7 6 9 1]
 [8 4 4 7 7]
 [4 3 2 9 2]]


In [199]:
!ls

a.npy  sample_data


In [201]:
b2 = np.random.randint(1,10,size=(5,5))
print(b2)

np.savez("ab",a2,b2)

[[7 9 9 5 4]
 [1 4 1 7 2]
 [8 1 5 6 2]
 [5 9 4 2 1]
 [6 7 1 4 2]]


In [202]:
!ls

ab.npz	a.npy  sample_data


In [203]:
npy = np.load("a.npy")
print(npy)

[[4 4 1 5 7]
 [8 3 9 7 6]
 [1 7 6 9 1]
 [8 4 4 7 7]
 [4 3 2 9 2]]


In [206]:
npz = np.load("ab.npz")
print(npz.files)
print(npz['arr_0'])
print(npz['arr_1'])

['arr_0', 'arr_1']
[[4 4 1 5 7]
 [8 3 9 7 6]
 [1 7 6 9 1]
 [8 4 4 7 7]
 [4 3 2 9 2]]
[[7 9 9 5 4]
 [1 4 1 7 2]
 [8 1 5 6 2]
 [5 9 4 2 1]
 [6 7 1 4 2]]


In [208]:
print(a2)
np.savetxt('a.csv',a2,delimiter=',')


[[4 4 1 5 7]
 [8 3 9 7 6]
 [1 7 6 9 1]
 [8 4 4 7 7]
 [4 3 2 9 2]]


In [209]:
!ls 

ab.npz	a.csv  a.npy  sample_data


In [210]:
!cat a.csv

4.000000000000000000e+00,4.000000000000000000e+00,1.000000000000000000e+00,5.000000000000000000e+00,7.000000000000000000e+00
8.000000000000000000e+00,3.000000000000000000e+00,9.000000000000000000e+00,7.000000000000000000e+00,6.000000000000000000e+00
1.000000000000000000e+00,7.000000000000000000e+00,6.000000000000000000e+00,9.000000000000000000e+00,1.000000000000000000e+00
8.000000000000000000e+00,4.000000000000000000e+00,4.000000000000000000e+00,7.000000000000000000e+00,7.000000000000000000e+00
4.000000000000000000e+00,3.000000000000000000e+00,2.000000000000000000e+00,9.000000000000000000e+00,2.000000000000000000e+00


In [211]:
csv = np.loadtxt('a.csv',delimiter=',')
print(csv)

[[4. 4. 1. 5. 7.]
 [8. 3. 9. 7. 6.]
 [1. 7. 6. 9. 1.]
 [8. 4. 4. 7. 7.]
 [4. 3. 2. 9. 2.]]


In [214]:
print(b2)
np.savetxt('b.csv',b2,delimiter = ',',fm t='%.2e',header='c1,c2,c3,c4,c5')

[[7 9 9 5 4]
 [1 4 1 7 2]
 [8 1 5 6 2]
 [5 9 4 2 1]
 [6 7 1 4 2]]


In [215]:
csv = np.loadtxt('b.csv',delimiter=',')
print(csv)

[[7. 9. 9. 5. 4.]
 [1. 4. 1. 7. 2.]
 [8. 1. 5. 6. 2.]
 [5. 9. 4. 2. 1.]
 [6. 7. 1. 4. 2.]]




---

